#!/usr/bin/env bash
reveal() {
    isZsh(){
        if command ps -p $$ | command grep -q zsh; then
            return 0
        else
            return 1
        fi
    }

    if isZsh; then
        setopt localoptions shwordsplit
    fi

  find_open_command_from_Operating_System() {
    local open_cmd
    OSTYPE="$(uname -s | tr 'A-Z' 'a-z')"

    case "$OSTYPE" in
    darwin*)  open_cmd='open' ;;
    cygwin*)  open_cmd='cygstart' ;;
    linux*)   [[ "$(uname -r)" != *icrosoft* ]] && open_cmd='nohup xdg-open' || {
                open_cmd='cmd.exe /c start ""'
                } ;;
    msys*)    open_cmd='start ""' ;;
    *)        echo "Platform $OSTYPE not supported"
                return 1
                ;;
    esac
    echo "$open_cmd"
}

  no_git_dir_no_args() { # length of "$1" is zero and is not a git directory.
    if [[ -z "$1" ]] && ! command git rev-parse --git-dir 2> /dev/null 1>&2; then
      return 0
    else
      return 1
    fi
  }

  no_git_dir_yes_args() { # length of "$1" is not zero and is not a git directory.
    if [[ -n "$1" ]] && ! command git rev-parse --git-dir 2> /dev/null 1>&2; then
      return 0
    else
      return 1
    fi
  }

  local open_cmd=$(find_open_command_from_Operating_System)
  if [[ -z "$GITHUB_ACCOUNT" ]]; then
    local name=$(git config user.name)
  else
    local name="$GITHUB_ACCOUNT"
   fi

  if no_git_dir_no_args $1; then
    $open_cmd "https://github.com/$name?tab=repositories" >/dev/null 2>&1
    unset -f find_open_command_from_Operating_System
    unset -f no_git_dir_no_args
    unset -f no_git_dir_yes_args
    return 0
  elif no_git_dir_yes_args $1; then
    for dir in "$@" ; do
      ( builtin cd "$dir" && reveal; )
    done
    unset -f find_open_command_from_Operating_System
    unset -f no_git_dir_no_args
    unset -f no_git_dir_yes_args
    unset -f isZsh
    return 0
  fi

  argValues="$@";
  command git remote -v | command grep -E "$(echo ${argValues/ /|})" | command grep 'heroku' | command grep fetch | command grep -o -E ':.*' | \
      cut -c 19- | command awk '{print $1}' | command sed 's@.git$@@' | \
      command xargs -I {} $open_cmd https://dashboard.heroku.com/apps/{} https://{}.herokuapp.com >/dev/null 2>&1
  {
      command git remote -v | command grep -E "$(echo ${argValues/ /|})" | command grep '@'  | command grep -o -E '@.*' | cut -c 2-
      command git remote -v | command grep -E "$(echo ${argValues/ /|})" | command grep '//' | command grep -o -E ':.*' | cut -c 4- | command grep -v 'heroku'
  } | command grep fetch | command sed 's@:@\/@g' | command awk '{print $1}' | sed 's@.git@@' | command xargs -I {} $open_cmd https://www.{} >/dev/null 2>&1

    unset -f find_open_command_from_Operating_System
    unset -f no_git_dir_no_args
    unset -f no_git_dir_yes_args
    unset -f isZsh

}

$(return 0 >/dev/null 2>&1) || reveal $@
